name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  - repository: vmchooserbackendv3
    type: github
    name: vmchooser/azure-vmchooser-backend-v3
    endpoint: vmchooser
trigger:
  batch: true
  branches:
    include:
    - master
stages:
#- stage: BuildContainerImage
#  displayName: Build & Push Container Image
#  jobs:
#  - job: BuildContainer
#    pool:
#      vmImage: 'ubuntu-latest'
#    steps:
#    - task: Docker@2
#      displayName: Login to ACR
#      inputs:
#        command: login
#        containerRegistry: vmchooserregistry
#    - task: Docker@2
#      displayName: Build and Push
#      inputs:
#        command: buildAndPush
#        repository: vmchooser/backendv3
#        tags: |
#          preview
#          $(Build.BuildId)
- stage: BuildHelmChart
  displayName: Update & Push Helm Chart
  jobs: 
  - job: BuildChart
    variables:
    - group: vmchooser
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - bash: |
        echo $(ARMCLIENTID) \| wc
        echo $(ARMCLIENTSECRET) \| wc
        az login --service-principal -u "$clientid" -p "$clientsecret" --tenant "$tenantid"
        az account set -s "$(armsubscriptionid)""
        az configure --defaults acr="$(vmchooserregistry)""
        az acr helm repo add  
      displayName: Enable ACR Integration
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in yaml files'
      inputs:
        targetFiles: |
          **/*.yaml
    - bash: |
        helm package ./vmchooserbackend/
      displayName: Package Helm Chart
    - bash: |
        az acr helm push ./*.tgz
      displayName: Push Helm Chart to ACR Repo
      