apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    version: #{Build.BuildNumber}#
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: #{Build.BuildNumber}#
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: #{Build.BuildNumber}#
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 80